INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Gobhi Prantha', 'North India', 4, ARRAY ['1 cup whole wheat flour', '1 and ½ TSP Salt', '2 cup shredded cauliflower', '½ cup chopped cilantro', '1 finely chopped green chilli', '½ TSP cumin seeds', '½ TSP ajvaiyan', 'Conola Oil'], ARRAY ['Add ½ TSP salt to the flour. Make dough like you make for chappaties.', 'Mix cauliflower, cilantro, green chilli, 1 TSP salt, cumin seeds, and ajvaiyan in a bowl. Let it sit for 5 minutes', 'Squeeze the water from this mixture. Just use both hands.', 'Make small balls of the dough.', 'Take each ball at a time, roll it so that it’s about 4 inches in diameter.', 'Put couple of spoons of the mixture in the middle, and fold the sides to close it (like a kachori)', 'Let it sit for couple of minutes with folded side down.', 'Turn it over (now the folded side is up), and roll it make it flat. Use dry flour as necessary.', 'Put it on hot tava, flip it couple of times, brush some oil on both sides. Once it’s as krispy as desired, serve with SmartBalance butter and hot tea made with soy milk.'], ARRAY ['Knife', 'Cutting board', 'food processor to shred cauliflower', 'tava', 'rolling pin'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Baked Potato', 'American', 4, ARRAY ['Beans.', '4 Potatoes.', 'Broccoli', 'Mushrooms', 'Shredded soy cheese', 'Avacado Salsa', 'Vegetable Oil'], ARRAY ['Cut brocolli and mushrooms.', 'Saute – add two table spoon oil in pan.', 'Cook the brocolli and mushrooms on low heat.', 'Wash potatoes thoroughly. “Fork” them at few places.', 'Brush them with vegetable oil.', 'Bake them in oven at 450 degrees for 45 minutes.', 'To serve, spread the potato open in a plate. Add beans, saute vegetables, soy cheese and avacado salsa on top.'], ARRAY ['Knife', 'pan', 'oven'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Brown Rice (Rice Cooker)', 'Indian - North', 1, ARRAY ['1 cup brown rice', '3 cups water', '1/2 tea spoon salt'], ARRAY ['Wash rice. Add in the water. Soak for 2 hours.', 'Add rice, water and salt in the cooker. Close the cooker. Turn it on.', 'Wait til the light turns on.', 'Open the cooker, and your rice are ready to be served.'], ARRAY ['Knife', 'rice cooker'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Brown Rice (pressure cooker)', '???', 4, ARRAY ["1 cup brown rice (Dynasty Extra Fancy, from Lucky's, Also New India Bazaar ???)", '2.5 cups water', '2 tea spoons vegetable oil', '1 tea spoon briani masala', '1/2 tea spoon salt'], ARRAY ['Wash rice. Add in the water. Soak for 20 minutes.', 'Add oil, salt, briani masala, rice and water in the cooker.', 'Close the cooker. Turn heat to medium.', 'After 1 whistle, change heat to low, and cook for another 15 minutes.', 'Turn off the heat. Let all the steam come out naturally, and your rice are ready to be served.'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Brown Rice (Zojirushi Cooker)', '???', 4, ARRAY ["1 cup brown rice (Dynasty Extra Fancy, from Lucky's, Also New India Bazaar ???)", '2.5 cups water', '2 tea spoons vegetable oil', '1 tea spoon briani masala', '1/2 tea spoon salt'], ARRAY ['Wash rice. Add in the water.', 'Add oil, salt, briani masala, rice and water in the cooker.', 'Set time to 1 hour.'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Tadka', 'North India', 1, ARRAY ['3/4 cup chopped onion', '2 tsp chopped ginger', '2 tbsp vegetable oil', '1 tsp jeera', '1 tomato', '1/2 tsp haldi'], ARRAY ['Heat oil in a pan.', 'Add jeera, ginger and onions', 'When onion are browned, add tomatoes.', 'When tomatoes are limp, add haldi'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Fresh Butter', 'North India', 4, ARRAY ['1 Small (236 ml) Heavy Whipping Cream', '1 ½ times tap water'], ARRAY ['Add whipping cream and water in a blender.', 'Run blender on “Low”'], ARRAY ['Blender'], 'Shar Goel', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Split Daal [Moong, Urad Channa]', 'Indian - North', 6, ARRAY ['4 cups water', '1 cup split moong daal  OR 1/2 cup split urad daal and 1/2 cup split channa daal', '2 tsp salt', '2 tbsp chopped cilantro', '1 cup Tadka', 'MDH Kitchen King Masala [Optional]'], ARRAY ['Add daal, water, and salt to pressure cooker. Set on medium heat.', 'After 1 whistle, turn off the heat. (about 8 minutes)', 'Check to see after 10 minutes that all the pressure has been released.', 'Add more water (if needed) and let it simmer in low heat for 10 minutes.', 'Add Tadka.', 'Simmer everything for another 3 minutes.', 'If needed/desired, add some Kitchen King masala.', 'Garnish with cilantro.', 'Serve with love and pride.'], ARRAY ['Knife', 'Cutting board', 'pressure cooker'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Whole Daal [Moong]', 'Indian - North', 6, ARRAY ['4 cups water', '1 1/3 cup whole moong daal', '2 tsp salt', '2 tbsp chopped cilantro', '1 cup Tadka', 'MDH Kitchen King Masala [Optional]'], ARRAY ['Add daal, water, and salt to pressure cooker. Set on medium heat.', 'After 2 whistles, turn off the heat. (about 8 minutes)', 'Check to see after 10 minutes that all the pressure has been released.', 'Add more water (if needed) and let it simmer in low heat for 10 minutes.', 'Add Tadka.', 'Simmer everything for another 3 minutes.', 'If needed/desired, add some Kitchen King masala.', 'Garnish with cilantro.', 'Serve with love and pride.'], ARRAY ['Knife', 'Cutting board', 'pressure cooker'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Rajmah', 'North India', 4, ARRAY ['1 Cup Rajmah', '1 TSP Salt', '½ Cup Tadka'], ARRAY ['Soak rajmah in water for 4 hours', 'Add 1 cup water, rajmah and salt in the pressure cooker', 'Let the cooker give 3 whistles', 'Open cooker, add tadka, and some more water. Close cooker', 'Let the cooker give 2 more whistles.', 'Open Cooker. Add more water if needed.'], ARRAY ['Pressure Cooker'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Sabji (without too much liquid)', 'Indian - North', 4, ARRAY ['1.5 pound of one or more types of green vegetables like egg plant, potato,         zuchini, mushrooms, peas', '3 TBSP oil', 'Half onion - chopped', 'one tomato - chopped', '1/2 spoon haldi', '1/2 spoon garam masala', '1 spoon jeera', '1 spoon salt'], ARRAY ['On medium heat, put oil, tomato, onion, and jeera in a pan.', 'Once the tomatoes are soft, add the rest.', 'Turn heat to low. Cover the pan with a lid.', 'Check in 7 minutes. Cook more depending on how much liquid is desired.'], ARRAY ['Pan', 'lid', 'knife', 'cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Pasta with Tomato Sauce', 'Italy', 1, ARRAY ['Pasta (Penne)', '1 cup Pasta  Sauce', '8 Ozs. Mushrooms', '1 Yellow Onion', '4 Small Zucchinis', '10 Basil Leaves', 'Pine Nuts', 'Canola oil', '1 Large Red Pepper', '1 TS Sugar', '1/4 TS Salt', '1/8 TS Black Pepper'], ARRAY ['Chop all the vegetables', 'Chop  basil leaves', 'Boil water in a pan', 'Add 1 spoon oil', 'Add pasta', 'On medium heat, boil pasta for 10 minutes or until tender', 'Strain pasta. Save water ???', 'In an empty pan, put 5 spoons of oil', 'Add vegetables', 'Saute them for 8 to 10 minutes', 'Add sauce, basil, pinenuts, salt, black pepper, sugar', 'Mix it well', 'Add pasta', 'Add more sauce if needed to make sure it seems enough.', 'Let it simmer on low heat for 10 minutes.', 'Serve with love and care.'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Gourmet Raviolli with sauted mushrooms and peppers', 'Italy', 4, ARRAY ['8 pieces Portobella Mushroom Raviolli [Trader Joes]', '12 pieces Butternut Squash         [Trader Joes]', '1 ½ cup mushrooms', '1 ½ sweet mini peppers (red, yellow, orange)', '1 bottle Tomato Basil Marinara sauce, Low Fat [Trader Joes]', '2 tea spoon brown sugar', '½ tea spoon black pepper', '1 tea spoon salt', '1 tea spoon dry basil', '2 table spoon oil'], ARRAY ['Boil water in a pan (high walls)', 'Add ½ tea spoon salt', 'Add all the raviolli in the boiling water', 'After 5 minutes, lower the heat to MEDIUM.', 'Let it boil for 5 more minutes. Lower the heat to LOW.', 'Cover the pan, and let it simmer for 8 more minutes.', 'Drain the water. Now the raviolli is ready to be mixed with the sauce.', 'Make thin slices of mushrooms and peppers.', 'Add oil in a shallow pan on medium heat.', 'Once the oil is hot, add sliced mushrooms and peppers.', 'Saute til they turn light brown.', 'Set them aside in a bowl.', 'Add ¾ bottle of marinara sauce in the same shallow pan on medium heat', 'Add ½ tea spoon salt, sugar, pepper and basil', 'Mix it well', 'Add raviolli. Lower the heat to LOW. Cover the pan.', 'Let it simmer for 5 minutes. Turn off the heat.', 'Serve raviolli and sauted vegetables in one place.'], ARRAY ['Knife', 'Cutting board', 'shallow pan', 'deep pan'], 'Dinesh Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Spanish Rice', 'Mexico', 8, ARRAY ['1 cup basmati rice', '1.5 cup water', '1 medium yellow onion', '1 small bag frozen mixed vegie [S&W brand: black beens, onion, red pepper, corn]', '2 table spoon canola oil', '1/2 tea spoon salt', '1/2 bunch cilantro', '1/2 cup boiled sauce from the Enchilada recepie'], ARRAY ['Wash rice (put in cooker), then add water and salt', 'Check after 15 minutes', 'Chop onion in small cubes', 'Chop cilantro', 'Place pan on medium heat. Add oil.', 'Add onion and vegies', 'Saute the mixture.', 'Add salt and rice', 'Cover the pan and lower the heat.', 'Check after 10 minutes.', 'Pour cooked rice in a glass tray', 'Pour Enchilada sauce over rice and mix it.', 'Sprinkle cilantro, and cover it with foil.'], ARRAY ['rice cooker', 'frying pan', 'glass tray'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Enchilada Sauce', 'Mexico', 8, ARRAY ['2 cans of fire roasted canned tomotoes', '1 large red bell pepper', '1 jalepeno pepper', '1 medium yellow onion', '1 large lemon', 'Spices: 1 tsp dil, 1 tspn rosemary, 2 tea tspn cumin powder, 2 tspn salt', '4 cup water'], ARRAY ['Cut bell pepper in half. De seed. Brush oil on the outside.', 'Brush oil on the jalepeno pepper.', 'Cut onion in half. Brush oil on all the sides.', 'Pre heat toaster oven to 400 degrees', 'Put everything up side down on the grill for 30 minutes.', 'Put canned tomotoes and grilled veggie in a blender.', 'Heat oil in a pan. Add puree, lemon juice, water, and spices.', 'Wait til it starts to boil.', 'Lower the heat, and let it simmer for 10 minutes.', 'Taste it and adjust speices as needed.'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Enchilada', 'Mexico', 20, ARRAY ['Mission Yellow Corn SuperSize (pack of 10). About 6 inch diameter', '3 Cup Frozen Yellow Corn', '1 Large Yellow Onion', '6 Green onion leaves', '5 Large Mushrooms', '1 bunch cilantro', '¼ lb spinach', '¾ cup soy cheese (Soyation)', '5 table spoon canola oil', '1 tea spoon Red chille', '2 tea spoon Salt'], ARRAY ['Chop onion, mushrooms in small cubes.', 'Chop cilantro in small pieces', 'Put Skillet on medium heat. Add oil. Add chopped vegetables (except cilantro) and corn. All salt and chille. Keep stirring til they turn brownish (well done).', 'Once it cools off, mix it with ½ cup cheese.', 'Brush oil on each tortilla. Heat both sides in frying pan. Flip it quickly. Do all 20 at the same time.', 'Take one tortilla. Put three table spoons of the vegie mixture, and roll the tortilla. Arrange them in the baking tray.', 'Pour bowling hot Enchilada sauce on each of the tortilla. Make sure they are well dipper in the sauce.', 'Sprinke chopeed green onion, cilantro and ¼ cup cheese.', 'Cover the tray with foil. Poke few holes in the foil.', 'Pre heat MW at 375 degrees.', 'Place the tray in the oven for 15 minutes. Then uncover the tray and keep for another 5 minutes.', 'Serve them along with mexican rice, beans, and avacado salsa.'], ARRAY ['1 frying pan', '1 Medium Size Skillet', '1 Knife', '1 baking tray', '1 bowl that can go on the stove'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Burrito', 'Mexican', 4, ARRAY ['Burrito Warps (Mission Multi Grain)', '3 Tomatoes', '¼ Iceburg Lettuce', '1/3 Onion', '1 Avacado', 'Canola Oil', '1 cup cooked brown rice', '½ cup shreded soy cheese', '2 servings of Beans.'], ARRAY ['Chop tomatoes, lettuce, onion, avacado.', 'Brush oil on both sides of each wrap. Warm in a pan.', 'Add beans, soy cheese, lettuce, tomato, onion, avacado, rice to the wrap.', 'Fold the wrap in form of a burrito.'], ARRAY ['Knife', 'pan'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Tostada', 'Mexico', 1, ARRAY ['6 medium size tomatoes', '1 head lettuce', '1 cup grated cheese', '½ cup sliced olives', 'Flat Los Pericos tostada shells', 'Avacado Salsa', 'Beans', 'Tofuti Sour Cream'], ARRAY ['Heat tostada shells in microwave', 'Spread beans', 'Add everything else as needed'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Penang Curry', 'Thai', 6, ARRAY ['½ cube extra firm tofu', '1 and ½ red bell pepper', '1 medium red onion', '10 oz mushrooms', '2 cups coconut milk', '1 cup water', '1 tbsp corn starch', '1 tbsp brown sugar', '1 tbsp soy sauce', '1 tbsp chilli garlic sause (Lee Kum Kee)', '3 tbsp home mode thai curry paste', 'Basil leaves', '1 tbsp lemmon juice', '1 tsp salt', '1 tbsp vegetable oil', '½ cup green onion'], ARRAY ['Put pan on low hear. Add oil add curry paste, and stir it for few minutes', 'Chop and add all the vegetables', 'Cover the pan.', 'In a separate bowl, add water, coconut milk, corn starch, soy sauce, salt, brown sugar, chilli garlic paste, and blend them together', 'Once the vegies are tender, add bowl ingridents to the pan.', 'Let it boil', 'Add thai currly leaves.', 'Squeeze lemon juice'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Tofu Cashew Curry', 'Milpitas', 6, ARRAY ['1 Extra Firm tofu', '20 cashews', '½ onion', '2 tomatoes', 'Ginger', 'Green Chille', 'Oil', 'Haldi, Salt', '2 spoon sugar', '1 spoon cardmum powder', '2 spoon coconut cream (optional)', 'Cilantro', '½ spoon Pulao Masala'], ARRAY ['Saute cashews, onion, ginger, chille in pan', 'Add tomatoes, haldi, salt', 'Once everything is soft, blend it with 1 cup of water', 'Pour everything in pan', 'Add two cups of water, tofu, sugar, coconut cream, cardmum, pulao masala', 'Cover the pan. Turn heat to medium.', 'Let it cook for 5 to 7 minutes.', 'Sprinkle cilantro and serve with pride.'], ARRAY ['Knife', 'Cutting board', 'blender'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Coconut Chicpea Spinach Curry', 'Richa’s inspiration', 5, ARRAY ['1 ½ cup dry garbango beans', '2 cans unsweetened cocunut milk', '3 cups chopped spinach', '3 ½ cups of vegetable broth', '1 large yellow onion chopped', '2 medium size tomatoes chopped', '1 inch sq ginger', '3 cloves garlic finely chopped', '3 tspn turmeric', '4 tspn salt', '3 tbsp vegetable oil', '1 tbsp lemon juice', '1 tspn roasted cumin powder (jeera)', '2 tbsp brown sugar', '1 tbsp shahi paneer masala (MDH)', '½ tspn red chilli powder'], ARRAY ['Soak garbajo beans over night. Boil them eldante.', 'Grind ginger in a food processor', 'Heat oil in pan on medium heat. Add ginger, garlic, onion. Saute til golden brown.', 'Add tomatoes. Saute til soft.', 'Add turmuric, cumin powder, chilli powder, shahi paneer masala, salt.', 'Add chik peas. Stir for 5 minutes.', 'Add coconut milk, broth and spinach. Cover it and let it simmer for 10 minutes', 'Add brown sugar and lemon juice. Stir for 2 minutes.', 'Serve with love and pride along side brown jasmine rice'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Pizza', 'Italy', 1, ARRAY ['1 cup maida (all purpose flour)', '½ cup mixed aata (no wheat)', '1 tbsp oil', '1 tbsp yeast (active dry, fast yeast for less time before preparation)', '1 tbsp sugar', '2 tbsp luke warm water', '¼ tbsp salt', '¼ tbsp Oregano and dil', '2 cups Ragu pasta sauce', '¼ to ½ basil sauce', '1 ½ shredded cheese [dairy or non-dairy]'], ARRAY ['Yeast: Put yeast, sugar, and luke warm water in a small cup. Stir. Leave it for 3 to 5 minutes It should froth (like soap)', 'Dough:', 'Pour flour, yeast froth, oil, salt, oregano, dil on the counter top', 'Slowly mix it with luke warm water', 'Knead it for 10 to 14 minutes with hands with full pressure. Aata should become sticky. Make it in a small bowl.', 'Brush oil in a bowl. Put the dough in the bowl. Cover it with damp cloth.', 'Place the bowl in room temperature. (in cold environment, use oven)', 'Because of the fast yeast, it should be ready in 90 minutes. The dough should double in size. Normal yeast will take 6 hours to double.', 'Final preparation:', 'Roll the dough with hand and rolling pin into thin to medium crust', 'Punch it with a fork. Very important to do this generously.', 'Mix pasta and basil sauces in a bowl.', 'Brush the pizza tray with oil', 'Put the rolled dough on the tray and spread the sauce and cheese', 'Add toppings as per taste.', 'Pre heat oven at 400 degrees at “Bake” setting', 'Place the tray in the oven for 15 minutes. Make sure the bottom is golden brown, and cheese should be melted', 'Change to “Broil” setting for 2 minutes to cook the toppings.', 'Take the tray out, sprinkle some chile flakes, and serve with love and pride.'], ARRAY ['Knife', 'Cutting board'], 'Venkat Gulamudi', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Veg Biriyani', 'Hydrabad', 4, ARRAY ['1 big potato - small cubes', '1 ½ red onion - small cubes', '¾ cup green peas', '¾ cup red or green bellpepper - small cubes', 'Fresh Ginger', '1 or 2 clove of garlic', '1 green chille', '3 tomotoes - small cubes', '3 bay leaf (Tej Patta)', '1 tbsp of 5 spice powder - Cing brand (Star Anise, Cinamon, Clove, Black pepper, Jeera)', '1 tspn Coriander (Sukha Dania)', '1 tbsp chunky chaat masala', '1 ½ tbsp of kitchen king masala', '1 tspn of Amchoor powder (Dry mango powder)', '2 tspn of chilli powder (optional)', '3 tspn Turmuric powder', '3 tspn Salt', '2 tbsp Ghee', '4 tbsp oil', '1 ½ cup yogurt', '2 ½ cups basmati rice', '¾ cup cauliflower', '8 green beens - small pieces', '1 carrot - small pieces', 'Cilantro'], ARRAY ['Chop all the vegetables', 'Mix all the masala powder + 1 tspn salt + some black pepper with yogurt in a open bowl. Keep it for 45 minutes. Call it marinade.', 'Mix rice with 3 cups of water, and cook it in a pressure cooker. Switch off after 1 whistle. Pour into a bowl and loosen the rice.', 'Add oil to a pan. Add onions. Cook little bit. Add potatos, carrorts, cauliflower and green beans. Add chilli powder and bay leafs. Cook for 2 minutes. Add green peas and bell pepper.  Cook for another 3 minutes. Add marinade. If too thick, add some water. Cook for 5 minutes.', 'Add ghee to pressure cooker on low flame. Add 1 inch layer of veggies. Add 1 ½ inch of layer of rice. Spread some cut cilantro. Add 1 inch layer of veggies. Add 1 ½ inch of rice. Spread some cut cilantro. Add leftover layer of veggies. Add final layer of rice. Add 1 tbsp of ghee. Add leftover cilantro on top. Sprikle ½ cup of water. Close the lid. Put on medium flame for 5 minutes.'], ARRAY ['Knife', 'Cutting board'], 'Venkat', 'Lunch');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Carrot Onion Raita', 'Hydrabad', 4, ARRAY ['Yogurt', '1 carrot grated', '1 onion - finely chopped', '1 green chilli - finally chopped', '1 Tomato - finally chopped', '1 tspn salt', '1/2 tspn sugar', '3 cups yogurt', 'Tadka', '1 tbsp oil', '½ tspn mustrad seeds', '½ tspn jeera', '5 leaves of curry patta', '½ tspn sugar'], ARRAY ['Mix everything “yogurt” together. Add water as desired', 'Add oil to a pan on low flame. Add “Tadka” ingridients. Cook for 1 minute til mustrad seeds are popping.', 'Add Tadka to the yogurt'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Lunch');

