INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, category) VALUES('Salsa', 'Mexican', 1,  ARRAY ['4 tomato', '1/4 white onion', '2 cloves of garlic', 'cilantro', 'lemon juice', 'salt'], ARRAY ['Chop everything. Add lemon juice.'], ARRAY ['Knife', 'Cutting board'], 'Snacks');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Avacado Salsa', 'Mexican', 1, ARRAY ['Salsa', '3 avacados'], ARRAY ['Cut avacados in small pieces. Mix in with the salsa'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Snacks');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Avacado Mango Salsa', 'Mexican', 1, ARRAY ['Avacado Salsa', '1 mango'], ARRAY ['Cut mango in small pieces. Mix in with Avacado salsa.'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Snacks');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Beans', 'Mexican', 4, ARRAY ['1 bowl of pinto beans', '1 cup Picante Salsa (medium spicy)', '1 cup chopped onion', '2 garlic cloves', '2 tsp salt', '1 tsp oil'], ARRAY ['Soak the beans for five hours.', 'Add oil, beans, garlic, and salt in a pressure cooker.', 'Boil at low heat until 5 whistles.', 'Mash the beans. Make sure they are just soggy not too watery.', "Mix 1 cup picante salsa, and onion while it's still on low heat.  Keep it for 15 minutes."], ARRAY ['Cooker', 'Masher'], 'Seema Goyal', 'Snacks');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Green Chutney', 'North India', 1, ARRAY ['1 bunch cilantro, chopped', '½ chopped onion', '2 tsp chopped ginger', '6 tsp lemon juice', '¾ tsp salt', '1 ½ tsp sugar', '½ cup mint leaves'], ARRAY ['Mix onion, ginger, and lemon juice in a blender at medium speed. [Doing this creates liquid that would then help blending cilantro and mint.]', 'Add cilantro and mint little by little', 'Blend in salt and sugar.'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Snacks');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Sprout Chaat', 'Indian - West', 1, ARRAY ['Sprouted Moong', 'Potato', 'Onion', 'Cilantro', 'Lemon', 'Tomato', 'Salt', 'Pepper', 'Jeera'], ARRAY ['Boil the potato', 'Boil some water in a pan', 'Place sprouted moong in a steaming basket', 'Place steaming basket inside the pan with hot water', 'Cover the pan with a lid.', 'Remove the steaming basket after few minutes', 'Add chopped onion, tomatos, potatos, and cilantro', 'Squeeze some lemon.', 'Sprinkle some salt, pepper and jeera'], ARRAY ['Knife', 'Cutting board', 'pan', 'steaming basket'], 'Seema Goyal', 'Snacks');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Golgappa Paani', 'North Indian', 1, ARRAY ['1 bunch of mint leaves', '2 tall glasses of cold water', '1 tbsp jeera (cumin)', '5 tbsp lemon juice', '1 tsp sugar', '3 tsp salt', '2 tsp of red pepper', '1 full cup of imli chutney'], ARRAY ['Combine mint leaves, imli chutney, 1 glass of water, lemon juice, and jeera in a blender.', 'Mix into smooth puree', '???'], ARRAY ['Knife', 'Cutting board'], 'Seema Goyal', 'Snacks');

INSERT INTO recipe(name, origin,servings, ingredients, process, equipment, contributor, category) VALUES('Stir Fry Tofu', 'Chinese', 2, ARRAY ['1 cup tofu from the Vietnamese place on Berryessa and Lundy', '1 cup mushrooms', '1 onion', '2 tsp connola oil', '1 tsp salt', '1 tsp soy sauce'], ARRAY ['Chop onion and mushrooms in small pieces', 'Cut Tofu in small squares', 'Add oil in pan, medium heat.', 'Once the oil is hot, add mushrooms, onions, and salt.', 'Once the mixture is semi soft, add tofu.', 'Slowly mix it all together as the Tofu gets some heat.', 'Add soy sauce. Mix it well.'], ARRAY ['Knife', 'Cutting board', 'Non-stick pan'], 'Seema Goyal', 'Snacks');

